### ISSUE TITLE
Discord link expired on Why OpenBeta page

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/collective.openbeta.io#14]
Discord invite link has expired
Page: https://collective.openbeta.io/why

<img width="683" alt="Screenshot 2023-07-06 at 10 16 11 AM" src="https://github.com/OpenBeta/collective.openbeta.io/assets/3805254/78a2da83-be0e-4249-a8d5-cac1bf89601e">

### To do:
- Use this new link https://discord.gg/w2KpQu2ca5
- Identify the why page and update the link

**Comment by shyamtawli** [comment]
Hey, Can I open a PR for it?

**Comment by vnugent** [comment]
Yes please.  I've assigned the issue to you.
